export const SET_NEW_PRODUCT = "SET_NEW_PRODUCT";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const RESET_CART = "RESET_CART";
export const SET_VALIDATION_CAPTCHA = "SET_VALIDATION_CAPTCHA";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";